site_name: Librarian
site_url: https://nautilus-cyberneering.github.io/librarian/
nav:
  - Home: index.md
  - Install: install.md
  - Development: development.md
  - Documentation: documentation.md
theme: readthedocs
