name: Publish to PyPI

#
# Package on PyPI: https://pypi.org/project/nautilus-librarian/
#

on:
  release:
    types: [ published ]

jobs:
  build:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.9'

      - name: Setup Poetry
        run: pip3 install poetry

      - name: Check Poetry
        run: poetry --version

      - name: Config Poetry for Cache
        if: ${{ !env.ACT }}
        run: poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        if: ${{ !env.ACT }}
        uses: actions/cache@v2.1.6
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-v0-${{ hashFiles('**/poetry.lock') }}

      - name: Install via Poetry
        run: poetry install

      - name: Run Pytest Test
        run: poetry run pytest --cov

      - name: Build Python package
        run: poetry build
    
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
