name: Test workflow integration using Poetry

on:
  push:
    branches: [main, issue-*]
  pull_request:
    branches: [main, issue-*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: "3.9"

      - name: Setup Poetry
        run: pip3 install poetry poetry-dynamic-versioning wheel

      - name: Check Poetry
        run: poetry --version

      - name: Config Poetry for Cache
        if: ${{ !env.ACT }}
        run: poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        if: ${{ !env.ACT }}
        uses: actions/cache@v2.1.6
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-v0-${{ github.event.repository.name }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install via Poetry
        run: |
          poetry install
          poetry build
          pip install --user "${{ github.workspace }}/dist/nautilus_librarian-$(poetry version --short)-py3-none-any.whl"

      - name: Invoke Librarian
        run: nautilus-librarian --version

      - name: Install via Poetry (dev env)
        if: ${{ env.ACT }}
        run: |
          poetry install
          poetry build
          ls "${{ github.workspace }}/dist/"
          pip install --user "${{ github.workspace }}/dist/nautilus_librarian-$(poetry version --short)-py3-none-any.whl"
          ls /root/.local/bin

      - name: Invoke Librarian (dev env)
        if: ${{ env.ACT }}
        run: |
          /root/.local/bin/nautilus-librarian --version
