name: Test workflow integration using Docker

on:
  push:
    branches: [main, issue-*]
  pull_request:
    branches: [main, issue-*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docker image
        run: ./bin/docker/build.sh

      - name: Invoke Librarian
        run: docker run --rm -i nautilus-librarian --version
